# Generated by Django 6.0.4 on 2026-09-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Company')),
                ('inquiry_type', models.CharField(choices=[('indri', 'Indri — Intelligent Monitoring'), ('cybersecurity', 'Cybersecurity'), ('cloud', 'Cloud Infrastructure'), ('enterprise-it', 'Enterprise IT Services'), ('partnership', 'Partnership'), ('general', 'General Inquiry'), ('other', 'Other')], default='general', max_length=30, verbose_name='Inquiry Type')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_responded', models.BooleanField(default=False, verbose_name='Responded?')),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('company', models.CharField(max_length=200, verbose_name='Company Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Work Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('industry', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('automotive', 'Automotive'), ('food-beverage', 'Food & Beverage'), ('pharmaceuticals', 'Pharmaceuticals'), ('textiles', 'Textiles'), ('electronics', 'Electronics'), ('chemicals', 'Chemicals'), ('engineering', 'Engineering & Fabrication'), ('other', 'Other Industrial')], max_length=50, verbose_name='Industry')),
                ('requirement', models.TextField(blank=True, verbose_name='Requirement Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Contacted?')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
            ],
            options={
                'verbose_name': 'Demo Request',
                'verbose_name_plural': 'Demo Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
